database:
  type: 'sqlite' # Opções válidas: 'sqlite' e 'mysql'
  mysql:
    address: 'localhost:3306'
    username: 'root'
    password: ''
    database: 'test'
  sqlite:
    file: 'database/database.db'

sellCommand: 'coins add @player @coins'

items:
  cacto:
    material: CACTUS
    itemName: 'Cacto'
    unitPrice: 10