database:
  type: 'sqlite' # Opções válidas: 'sqlite' e 'mysql'
  mysql:
    address: 'localhost:3306'
    username: 'root'
    password: ''
    database: 'test'
  sqlite:
    file: 'database/database.db'

# Nome da economia
economyName: 'Coins'

# Comando que será executado quando vender itens
sellCommand: 'coins add @player @coins'

# Lista de itens que serão armazenados
items:
  cacto:
    material: CACTUS
    itemName: 'Cacto'
    unitPrice: 10